#!/usr/bin/env bash
#Script that installs web server and redirects /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \ \ \ \ location /redirect_me {\n\ \ \ \ \ \ \ \ return 301 https:github.com/amateurManu;\n\ \ \ \ }' /etc/nginx/sites-available/default
service nginx start
